blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: 🐞 Bug Report
    description: Report a problem you encountered with the Telegram bot
    file: bug-report.yml
  - name: ✨ Feature Request
    description: Suggest a feature or improvement for the bot
    file: feature-request.yml
  - name: ❓ Question / Help
    description: Ask a question or request help related to the bot
    file: question.yml
