name: ✨ Feature Request
description: Suggest an improvement or a new feature for the Telegram bot
title: "[Feature] "
labels: [enhancement, telegram-bot]
assignees: [mnasibzade]
body:
  - type: input
    attributes:
      label: Feature or Command Name
      description: What should this feature or command be called?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the feature
      description: Describe your idea and how it would help users
      placeholder: "I'd like to suggest a new command /example that does..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Any other details, examples, or comparisons?
