name: ❓ Question / Help
description: Ask a question or request help related to the bot
title:                        "[Question] "
labels: [question, telegram-bot]
assignees: [mnasibzade]
body:
  - type: textarea
    attributes:
      label: Your Question
      description: Write your question clearly and in detail
      placeholder: "How does the /alpha command work for unofficial builds?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: What have you tried?
      description: Let us know if you've already tried something or checked docs
